version: '2'

volumes:
  redis-data: {}
  mysql: {}

services:
  grape-slack-db:
    image: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: grapepass
      MYSQL_DATABASE: grape_slack
    ports:
      - '3306'
    volumes:
      - mysql:/var/lib/mysql

  grape-slack-redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass foobared
    volumes:
       - redis-data:/data

  grape-slack:
    image: grape_slack
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - grape-slack-db
    env_file: .env
    volumes:
      - .:/grape_slack
