- include_vars: gce_auth.yml
- include_vars: instance.yml

- name: Launch instances (grape-slack-ansible)
  gce:
    instance_names: "{{ names }}"
    machine_type: "{{ machine_type }}"
    image: "{{ image }}"
    service_account_email: "{{ service_account_email }}"
    credentials_file: "{{ credentials_file }}"
    project_id: "{{ project_id }}"
    zone: "{{ zone }}"
    metadata : '{ "startup-script" : "apt-get update" }'
    tags: ['webserver','http-server', 'https-server']
  register: gce

- name: Http Config
  gce_net:
    name: default
    subnet_name: default

- name: Wait for SHH to come up
  wait_for: host={{ item.public_ip }} port=22 delay=10 timeout=60
  with_items: "{{ gce.instance_data }}"

- name: Add host to groupname
  add_host: hostname={{ item.public_ip }} groupname=grape-slack
  with_items: "{{ gce.instance_data }}"

- name: set_fact external ip
  set_fact: external_ip={{ item.public_ip }}
  with_items: "{{ gce.instance_data }}"

- name: set_fact web server name
  set_fact: web_server={{ names }}

# このインスタンスの外部IPをファイルに書き出しておく
- name: Create create-cloud_sql/web_server.yml
  template: >
    src=web_server.yml.j2
    dest=roles/create-cloud_sql/vars/web_server.yml
    owner={{ ansible_ssh_user }}
    mode=0644

- name: Create nginx-web_server/main.yml
  template: >
    src=web_server.yml.j2
    dest=roles/nginx-web_server/vars/main.yml
    owner={{ ansible_ssh_user }}
    mode=0644

